version: '3.7'

services:
  budget-server:
    build:
      context: .
      dockerfile: apps/budget-servers/Dockerfile
      target: budget-server
    profiles:
      - budget-server
    ports:
      - '${BUDGET_SERVER_PORT}:${BUDGET_SERVER_PORT}'
    environment:
      BUDGET_SERVER_PORT: ${BUDGET_SERVER_PORT}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_SERVER: ${MONGO_SERVER}
      MONGO_AUTH_SOURCE: ${MONGO_AUTH_SOURCE}
  mongo:
    image: mongo
    profiles:
      - budget-server-mongo
      - budget-server
    ports:
      - '${MONGO_PORT}:${MONGO_PORT}'
    volumes:
      - './scripts/db/mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
  mongo-express:
    image: mongo-express
    profiles:
      - budget-server-mongo
      - budget-server
    depends_on:
      - mongo
    restart: always
    ports:
      - '${MONGO_EXPRESS_PORT}:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  zdm-db:
    image: postgres
    profiles:
      - zdm
      - zdm-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      -
  adminer:
    image: adminer
    profiles:
      - zdm
      - zdm-postgres
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: zdm-db
      ADMINER_DESIGN: dracula
    ports:
      - '${ADMINER_PORT}:8080'

volumes:
  data:
