version: '3.7'

services:
  budget-server:
    build:
      context: .
      dockerfile: apps/budget-servers/Dockerfile
      target: budget-server
    profiles:
      - server
    ports:
      - '${BUDGET_SERVER_PORT}:${BUDGET_SERVER_PORT}'
    environment:
      BUDGET_SERVER_PORT: ${BUDGET_SERVER_PORT}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_SERVER: ${MONGO_SERVER}
      MONGO_AUTH_SOURCE: ${MONGO_AUTH_SOURCE}
  mongo:
    image: mongo
    profiles:
      - mongo
      - server
    ports:
      - '${MONGO_PORT}:${MONGO_PORT}'
    volumes:
      - './scripts/db/mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
  mongo-express:
    image: mongo-express
    profiles:
      - mongo
      - server
    depends_on:
      - mongo
    restart: always
    ports:
      - '${MONGO_EXPRESS_PORT}:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
volumes:
  data:
