version: 2.1
parameters:
  GHA_Event:
    type: string
    default: ""
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""
executors:
  node-rush:
    docker:
      - image: cimg/node:19.5.0
jobs:
  update-and-build:
    executor: node-rush
    working_directory: ~/project/apps/budget-servers
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Install Rush
          command: npm install --prefix=$HOME/.local --global @microsoft/rush
      - run:
          name: My files
          command: rush -h
      - run:
          name: Build Project
          command: make build

workflows:
  build:
    when: << pipeline.parameters.GHA_Action >>
    jobs:
      - update-and-build