import { Inter } from 'next/font/google';
import 'bootstrap/dist/css/bootstrap.css';
import './globals.scss';
import { InputCommand } from '@/components/atoms/InputCommand/InputCommand';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container-lg">
          <div className="mb-3">
            <InputCommand />
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
