# fly.toml app configuration file generated for budget-servers-dev on 2023-10-21T07:58:49-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "budget-servers-dev"
primary_region = "eze"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  BUDGET_SERVER_PORT = 3000
